import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
	title: "Portfolio - Next.js",
	description: "Generated by create next app",
	icons: {
		icon: "/fox_white.png",
	},
};

// src/app/main/layout.tsx
export default function MainLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return <div className="custom-main-layout">{children}</div>;
}
